# Generated by Django 5.1.3 on 2024-11-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_can_ho', models.CharField(max_length=20, unique=True)),
                ('toa_nha', models.CharField(max_length=50)),
                ('so_tang', models.IntegerField()),
                ('dien_tich', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trang_thai', models.CharField(choices=[('Trống', 'Trống'), ('Đã thuê', 'Đã thuê')], default='Trống', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CuDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=10)),
                ('dia_chi', models.CharField(max_length=255)),
                ('ngay_dang_ky', models.DateTimeField(auto_now_add=True)),
                ('can_ho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.canho')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HopDongThue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('gia_thue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('can_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.canho')),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cudan')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuRaVao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_vao', models.DateTimeField(blank=True, null=True)),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cudan')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiNha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=10)),
                ('quan_he', models.CharField(choices=[('Cha', 'Cha'), ('Mẹ', 'Mẹ'), ('Con', 'Con'), ('Vợ/Chồng', 'Vợ/Chồng'), ('Khác', 'Khác')], max_length=50)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('cu_dan_chinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_nha', to='myapp.cudan')),
            ],
        ),
        migrations.CreateModel(
            name='PhiDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_phi', models.CharField(choices=[('Điện', 'Điện'), ('Nước', 'Nước'), ('Phí quản lý', 'Phí quản lý')], max_length=50)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thang', models.DateField()),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cudan')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=100)),
                ('noi_dung', models.TextField()),
                ('ngay_gui', models.DateTimeField(auto_now_add=True)),
                ('nguoi_nhan', models.ManyToManyField(to='myapp.cudan')),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauBaoTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=100)),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Đang xử lý', max_length=20)),
                ('cu_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cudan')),
            ],
        ),
    ]
