# Generated by Django 5.1.3 on 2024-12-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chusohuu_tiennghi_canho_huong_can_ho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='chu_so_huu',
            field=models.ManyToManyField(blank=True, related_name='can_ho', to='myapp.chusohuu'),
        ),
    ]
